### ISSUE TITLE
LSI#build_index is very slow

### ISSUE THREAD

**Issue by danbernier** [jekyll/classifier-reborn#14]
I have code something like this:

``` ruby
lsi = ClassifierReborn::LSI.new(auto_rebuild: false)
data.each do |row|
  lsi.add_item(row['foo'], row['bar'])
end
lsi.build_index
```

...and `build_index` runs very slowly on lots of items.
- With ~10 items, it runs in <1 second
- With ~20 items, it runs in ~15 seconds
- With ~30 items, it runs in ~130 seconds

I tracked it down to #build_index by disabling `auto_rebuild`. From there, I tracked it through LSI#build_reduced_matrix, to the monkey-patched extension `Matrix#SV_decomp`, inside the 3-level nested loop:

``` ruby
     while true do
       for row in (0...qrot.row_size-1) do
         for col in (1..qrot.row_size-1) do
```

Based on the name `SV_decomp`, I'll hazard a guess that this is supposed to be a [Singular Value Decomposition](http://en.wikipedia.org/wiki/Singular_value_decomposition) (which I just discovered). A quick search turned up the [Ruby-SVD gem](https://github.com/willcannings/Ruby-SVD), which could be an option.

I don't understand any of the math, or much of this gem's layout yet, but wanted to record my findings.

**Comment by nhoizey** [comment]
It seems I have a blocking issue with LSI.

I have this issue I wrote about on Stackoverflow: <http://stackoverflow.com/questions/30038899/jekyll-build-stuck-in-rebuilding-index-stage>

A friend told me to try without LSI, and indeed I have not the issue anymore.

Any progress on this since november?

**Comment by Ch4s3** [comment]
@nhoizey Sadly no. We still need to rewrite the SVD, and I haven't had to to relearn that corner of linear algebra to rewrite it. If you know anyone who is both a Rubyist and handy at matrix manipulation, they could be super helpful here! 

Otherwise I'll try my best to work on it, but I'm a bit swamped right now.

**Comment by nhoizey** [comment]
@Ch4s3 ok, thanks for the quick answer! I will do without LSI now, and watch the issue to know when any progress is made. I will try to find if someone can help: https://twitter.com/nhoizey/status/595618088369938432

**Comment by Ch4s3** [comment]
Awesome, thanks! If I decide I absolutely can't do it, I'll consider putting a bounty on it down the line.

**Comment by inspire22** [comment]
+1 Thanks, I've been wondering why LSI seems so crazy slow once I get above 100 documents...

**Comment by jayniz** [comment]
Been bitten by this too :)

**Comment by kreynolds** [comment]
I just did a bunch of performance improvements for the GSL (some for pure-ruby as well) and I thought I'd add some benchmarks here .. I index 130 documents in 4 seconds on my 2013 macbook pro. If you are having performance issues, you might want to check out the GSL variant, especially once #46 gets merged

**Comment by Ch4s3** [comment]
Based on #46 and the need to do the rewrite #30 that may or may not happen, I'm calling this closed.
